name: "build-tauri-on-pr"
on: [pull_request]

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install webkit2gtk (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev
    #- name: install javascript deps and build bundle
    #  run: make deps
    - name: install javascript deps and build bundle
      run: yarn && make build-js
    - name: run build
      run: make build-release
    - name: upload built binaries
      uses: actions/upload-artifact@v2
      with:
        name: executable-${{ matrix.platform }}
        path: desktop-tauri/target/release/twinleaf-tio-desktop*
        retention-days: 7
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        projectPath: desktop-tauri/
        distPath: ../desktop-web/
    - name: upload built bundles
      uses: actions/upload-artifact@v2
      with:
        name: bundle-${{ matrix.platform }}
        path: desktop-tauri/target/release/bundle/*/twinleaf-tio-desktop*
        retention-days: 7
